pool:
  vmImage: 'windows-2019'

# Variables
variables:
  version: 16-10-4
  vs2019InstallerFile: vs_enterprise__1251177795.1627255683.exe
  repositoryName: vs2019_Azure_DevOps
  # Secret Variables
#  MAPPED_FTP_HOST: $(FTP_HOST)
#  MAPPED_FTP_USER: $(FTP_USER)
#  MAPPED_FTP_PWD: $(FTP_PWD)
  MAPPED_MEGA_USERNAME: $(MEGA_USERNAME)
  MAPPED_MEGA_PASSWORD: $(MEGA_PASSWORD)

steps:
  - script: |
      $(vs2019InstallerFile) --passive --layout VS2019-$(version)_layout_$(Build.SourceBranchName) --lang en-US --add Microsoft.VisualStudio.Workload.$(Build.SourceBranchName) --includeRecommended --includeOptional
      dir VS2019-$(version)_layout_$(Build.SourceBranchName)
    displayName: 'Download VS2019 $(version) $(Build.SourceBranchName) Items'
    condition: and(ne(variables['Build.SourceBranchName'], 'NativeDesktop'), ne(variables['Build.SourceBranchName'], 'Universal'), ne(variables['Build.SourceBranchName'], 'NativeGame'))
    timeoutInMinutes: 0
  - script: |
      $(vs2019InstallerFile) --passive --layout VS2019-$(version)_layout_$(Build.SourceBranchName) --lang en-US --add Microsoft.VisualStudio.Workload.$(Build.SourceBranchName) --includeRecommended
      dir VS2019-$(version)_layout_$(Build.SourceBranchName)
    displayName: 'Download VS2019 $(version) $(Build.SourceBranchName) (Reduced) Items'
    condition: or(eq(variables['Build.SourceBranchName'], 'NativeDesktop'), eq(variables['Build.SourceBranchName'], 'NativeGame'))
    timeoutInMinutes: 0
  - script: |
      $(vs2019InstallerFile) --passive --layout VS2019-$(version)_layout_Universal --lang en-US --add Microsoft.VisualStudio.Workload.$(Build.SourceBranchName) --includeRecommended --add Microsoft.VisualStudio.ComponentGroup.UWP.VC --add Microsoft.VisualStudio.ComponentGroup.UWP.VC.v141
      dir VS2019-$(version)_layout_$(Build.SourceBranchName)
    displayName: 'Download VS2019 $(version) Universal (Reduced) Items with UWP C++ tools'
    condition: eq(variables['Build.SourceBranchName'], 'Universal')
    timeoutInMinutes: 0
  # Check for Zip
  - script: CALL Info-ZIP-3.0\zip.exe --version
    displayName: 'Check for Zip'
  # Compress Workload Directory & Verify Compress
  - script: |
      CALL Info-ZIP-3.0\zip.exe -r VS2019-$(version)_layout_$(Build.SourceBranchName).zip VS2019-$(version)_layout_$(Build.SourceBranchName)
      echo
      echo Current Directory Contents
      echo --------------------------------------------------------
      dir
    displayName: 'Zip VS2019 $(version) $(Build.SourceBranchName) Directory'
  # # Upload Workload Directory Zip File
  # - task: FtpUpload@2
  #   displayName: 'FTP Upload VS2019 $(version) $(Build.SourceBranchName) Directory Zip File'
  #   inputs:
  #     credentialsOption: inputs
  #     serverUrl: 'ftp://$(MAPPED_FTP_HOST)'
  #     username: $(MAPPED_FTP_USER)
  #     password: $(MAPPED_FTP_PWD)
  #     # TODO : Add option for file instead of directory
  #     rootDirectory: '.'
  #     remoteDirectory: '/public_html/files/$(repositoryName)/$(Build.SourceVersion)'
  #     filePatterns: 'VS2019-$(version)_layout_$(Build.SourceBranchName).zip'
  - publish: VS2019-$(version)_layout_$(Build.SourceBranchName).zip
    artifact: VS2019 $(version) $(Build.SourceBranchName)
  - script: |
      CALL megatools-1.11.0-git-20210505-win64\megatools.exe test -d /Root/$(repositoryName) --username $(MAPPED_MEGA_USERNAME) --password $(MAPPED_MEGA_PASSWORD)
      IF ERRORLEVEL 1 (
        CALL megatools-1.11.0-git-20210505-win64\megatools.exe mkdir /Root/$(repositoryName) --username $(MAPPED_MEGA_USERNAME) --password $(MAPPED_MEGA_PASSWORD)
      )
    displayName: 'Mega : Check & Create (if not available) $(repositoryName) Folder'
  - script: CALL megatools-1.11.0-git-20210505-win64\megatools.exe put --path /Root/$(repositoryName)/VS2019-$(version)_layout_$(Build.SourceBranchName).zip VS2019-$(version)_layout_$(Build.SourceBranchName).zip --username $(MAPPED_MEGA_USERNAME) --password $(MAPPED_MEGA_PASSWORD)
    displayName: 'Mega : Upload VS2019 $(version) $(Build.SourceBranchName) Directory Zip File'
