pool:
  vmImage: 'vs2017-win2016'

# Variables
variables:
  workload: ManagedDesktop
  
steps:
- script: | 
    vs_Enterprise.exe --passive --layout VS2019_layout_$(workload) --lang en-US --add Microsoft.VisualStudio.Workload.$(workload) --includeRecommended --includeOptional
    dir VS2019_layout_$(workload)
  displayName: 'Download VS2019 Workload Items'
  continueOnError: true 
  timeoutInMinutes: 0
# Check for Zip
- script: zip.exe --version
  displayName: 'Check for Zip'
# Compress Workload Directory & Verify Compress
- script: |
    zip.exe -r VS2019_layout_$(workload).zip VS2019_layout_$(workload) 
    echo 
    echo Current Directory Contents
    echo --------------------------------------------------------
    dir
  displayName: 'Zip Workload Directory'
# Upload Repository Zip File
- task: FtpUpload@1
  displayName: 'FTP Upload Directory Zip File'
  inputs:
    credentialsOption: inputs
    serverUrl: 'ftp://192.254.233.216'
    username: 'root@alaneesgroup.com'
    password: 9895204814
    # TODO : Add option for file instead of directory
    rootDirectory: '.'
    remoteDirectory: '/azure_devops/vs2019_16-5-3_full'
    filePatterns: 'VS2019_layout_$(workload).zip'