pool:
  vmImage: 'windows-2019'

# Variables
variables:
  version: 16-8-4
  vs2019InstallerFile: vs_enterprise__1935407894.1609606158.exe
  # Secret Variables
  MAPPED_FTP_HOST: $(FTP_HOST)
  MAPPED_FTP_USER: $(FTP_USER)
  MAPPED_FTP_PWD: $(FTP_PWD)
  
steps:
- script: | 
    $(vs2019InstallerFile) --passive --layout VS2019-$(version)_layout_$(Build.SourceBranchName) --lang en-US --add Microsoft.VisualStudio.Workload.$(Build.SourceBranchName) --includeRecommended
    dir VS2019-$(version)_layout_$(Build.SourceBranchName)
  displayName: 'Download VS2019 $(version) $(Build.SourceBranchName) Items'
  continueOnError: true 
  timeoutInMinutes: 0
# Check for Zip
- script: zip.exe --version
  displayName: 'Check for Zip'
# Compress Workload Directory & Verify Compress
- script: |
    zip.exe -r VS2019-$(version)_layout_$(Build.SourceBranchName).zip VS2019-$(version)_layout_$(Build.SourceBranchName) 
    echo 
    echo Current Directory Contents
    echo --------------------------------------------------------
    dir
  displayName: 'Zip Workload Directory'
# Upload Repository Zip File
- task: FtpUpload@1
  displayName: 'FTP Upload Directory Zip File'
  inputs:
    credentialsOption: inputs
    serverUrl: 'ftp://$(MAPPED_FTP_HOST)'
    username: $(MAPPED_FTP_USER)
    password: $(MAPPED_FTP_PWD)
    # TODO : Add option for file instead of directory
    rootDirectory: '.'
    remoteDirectory: '/public_html/files/azure_devops/vs2019_$(version)'
    filePatterns: 'VS2019-$(version)_layout_$(Build.SourceBranchName).zip'
